/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 133
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 61
#define ALIAS_COUNT 0
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  anon_sym_i32 = 3,
  anon_sym_f32 = 4,
  anon_sym_string = 5,
  sym_identifier = 6,
  sym_string = 7,
  sym_int = 8,
  sym_true = 9,
  sym_false = 10,
  sym_fn_keyword = 11,
  sym_return_keyword = 12,
  sym_var_keyword = 13,
  sym_const_keyword = 14,
  sym_union_keyword = 15,
  sym_struct_keyword = 16,
  sym_package_keyword = 17,
  sym_if_keyword = 18,
  sym_greater_or_equal_than_operator = 19,
  sym_less_or_equal_than_operator = 20,
  sym_greater_than_operator = 21,
  sym_less_than_operator = 22,
  sym_equality_operator = 23,
  anon_sym_SPACE = 24,
  anon_sym_LPAREN = 25,
  anon_sym_RPAREN = 26,
  anon_sym_LBRACE2 = 27,
  anon_sym_EQ = 28,
  anon_sym_COMMA = 29,
  anon_sym_COMMA2 = 30,
  anon_sym_LF = 31,
  anon_sym_SEMI = 32,
  sym_source_file = 33,
  sym__definition = 34,
  sym__statement = 35,
  sym_block = 36,
  sym_type = 37,
  sym_expression = 38,
  sym__comparison_operator = 39,
  sym_function_definition = 40,
  sym_struct_definition = 41,
  sym_union_definition = 42,
  sym_package_definition = 43,
  sym__boolean_expression = 44,
  sym__comparison_expression = 45,
  sym__simple_expression = 46,
  sym_const_statement = 47,
  sym_var_statement = 48,
  sym_return_statement = 49,
  sym_if_statement = 50,
  sym_constant = 51,
  sym_parameter = 52,
  sym_parameters = 53,
  sym_struct_field = 54,
  sym__terminator = 55,
  aux_sym_source_file_repeat1 = 56,
  aux_sym_block_repeat1 = 57,
  aux_sym_struct_definition_repeat1 = 58,
  aux_sym_parameters_repeat1 = 59,
  aux_sym_struct_field_repeat1 = 60,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_i32] = "i32",
  [anon_sym_f32] = "f32",
  [anon_sym_string] = "string",
  [sym_identifier] = "identifier",
  [sym_string] = "string",
  [sym_int] = "int",
  [sym_true] = "true",
  [sym_false] = "false",
  [sym_fn_keyword] = "fn_keyword",
  [sym_return_keyword] = "return_keyword",
  [sym_var_keyword] = "var_keyword",
  [sym_const_keyword] = "const_keyword",
  [sym_union_keyword] = "union_keyword",
  [sym_struct_keyword] = "struct_keyword",
  [sym_package_keyword] = "package_keyword",
  [sym_if_keyword] = "if_keyword",
  [sym_greater_or_equal_than_operator] = "greater_or_equal_than_operator",
  [sym_less_or_equal_than_operator] = "less_or_equal_than_operator",
  [sym_greater_than_operator] = "greater_than_operator",
  [sym_less_than_operator] = "less_than_operator",
  [sym_equality_operator] = "equality_operator",
  [anon_sym_SPACE] = " ",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ") ",
  [anon_sym_LBRACE2] = " {",
  [anon_sym_EQ] = " = ",
  [anon_sym_COMMA] = ", ",
  [anon_sym_COMMA2] = ",",
  [anon_sym_LF] = "\n",
  [anon_sym_SEMI] = ";",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym__statement] = "_statement",
  [sym_block] = "block",
  [sym_type] = "type",
  [sym_expression] = "expression",
  [sym__comparison_operator] = "_comparison_operator",
  [sym_function_definition] = "function_definition",
  [sym_struct_definition] = "struct_definition",
  [sym_union_definition] = "union_definition",
  [sym_package_definition] = "package_definition",
  [sym__boolean_expression] = "_boolean_expression",
  [sym__comparison_expression] = "_comparison_expression",
  [sym__simple_expression] = "_simple_expression",
  [sym_const_statement] = "const_statement",
  [sym_var_statement] = "var_statement",
  [sym_return_statement] = "return_statement",
  [sym_if_statement] = "if_statement",
  [sym_constant] = "constant",
  [sym_parameter] = "parameter",
  [sym_parameters] = "parameters",
  [sym_struct_field] = "struct_field",
  [sym__terminator] = "_terminator",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_struct_definition_repeat1] = "struct_definition_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
  [aux_sym_struct_field_repeat1] = "struct_field_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_i32] = anon_sym_i32,
  [anon_sym_f32] = anon_sym_f32,
  [anon_sym_string] = anon_sym_string,
  [sym_identifier] = sym_identifier,
  [sym_string] = sym_string,
  [sym_int] = sym_int,
  [sym_true] = sym_true,
  [sym_false] = sym_false,
  [sym_fn_keyword] = sym_fn_keyword,
  [sym_return_keyword] = sym_return_keyword,
  [sym_var_keyword] = sym_var_keyword,
  [sym_const_keyword] = sym_const_keyword,
  [sym_union_keyword] = sym_union_keyword,
  [sym_struct_keyword] = sym_struct_keyword,
  [sym_package_keyword] = sym_package_keyword,
  [sym_if_keyword] = sym_if_keyword,
  [sym_greater_or_equal_than_operator] = sym_greater_or_equal_than_operator,
  [sym_less_or_equal_than_operator] = sym_less_or_equal_than_operator,
  [sym_greater_than_operator] = sym_greater_than_operator,
  [sym_less_than_operator] = sym_less_than_operator,
  [sym_equality_operator] = sym_equality_operator,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE2] = anon_sym_LBRACE2,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COMMA2] = anon_sym_COMMA2,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym__statement] = sym__statement,
  [sym_block] = sym_block,
  [sym_type] = sym_type,
  [sym_expression] = sym_expression,
  [sym__comparison_operator] = sym__comparison_operator,
  [sym_function_definition] = sym_function_definition,
  [sym_struct_definition] = sym_struct_definition,
  [sym_union_definition] = sym_union_definition,
  [sym_package_definition] = sym_package_definition,
  [sym__boolean_expression] = sym__boolean_expression,
  [sym__comparison_expression] = sym__comparison_expression,
  [sym__simple_expression] = sym__simple_expression,
  [sym_const_statement] = sym_const_statement,
  [sym_var_statement] = sym_var_statement,
  [sym_return_statement] = sym_return_statement,
  [sym_if_statement] = sym_if_statement,
  [sym_constant] = sym_constant,
  [sym_parameter] = sym_parameter,
  [sym_parameters] = sym_parameters,
  [sym_struct_field] = sym_struct_field,
  [sym__terminator] = sym__terminator,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_struct_definition_repeat1] = aux_sym_struct_definition_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
  [aux_sym_struct_field_repeat1] = aux_sym_struct_field_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [sym_fn_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_return_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_var_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_const_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_union_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_package_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_if_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_greater_or_equal_than_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_less_or_equal_than_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_greater_than_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_less_than_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_equality_operator] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__comparison_operator] = {
    .visible = false,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_union_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_package_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__boolean_expression] = {
    .visible = false,
    .named = true,
  },
  [sym__comparison_expression] = {
    .visible = false,
    .named = true,
  },
  [sym__simple_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_const_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_var_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_field] = {
    .visible = true,
    .named = true,
  },
  [sym__terminator] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_struct_field_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_condition = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_condition] = "condition",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_condition, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 4,
  [8] = 5,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 11,
  [13] = 13,
  [14] = 10,
  [15] = 13,
  [16] = 16,
  [17] = 9,
  [18] = 18,
  [19] = 18,
  [20] = 18,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 22,
  [29] = 22,
  [30] = 30,
  [31] = 25,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 27,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 25,
  [51] = 24,
  [52] = 26,
  [53] = 53,
  [54] = 54,
  [55] = 35,
  [56] = 39,
  [57] = 40,
  [58] = 30,
  [59] = 25,
  [60] = 60,
  [61] = 38,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 37,
  [66] = 36,
  [67] = 34,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 75,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 84,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 27,
  [93] = 93,
  [94] = 94,
  [95] = 30,
  [96] = 82,
  [97] = 97,
  [98] = 98,
  [99] = 82,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 39,
  [109] = 109,
  [110] = 110,
  [111] = 101,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 94,
  [117] = 117,
  [118] = 94,
  [119] = 119,
  [120] = 88,
  [121] = 93,
  [122] = 122,
  [123] = 123,
  [124] = 105,
  [125] = 106,
  [126] = 126,
  [127] = 100,
  [128] = 100,
  [129] = 104,
  [130] = 112,
  [131] = 85,
  [132] = 132,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(57);
      ADVANCE_MAP(
        ' ', 2,
        '"', 10,
        '(', 108,
        ')', 3,
        ',', 113,
        ';', 116,
        '<', 104,
        '=', 17,
        '>', 103,
        'c', 39,
        'f', 15,
        'i', 16,
        'p', 18,
        'r', 26,
        's', 50,
        't', 41,
        'u', 34,
        'v', 20,
        '{', 58,
        '}', 59,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        ' ', 2,
        '"', 10,
        '(', 108,
        ')', 3,
        ',', 113,
        ';', 116,
        '<', 104,
        '=', 17,
        '>', 103,
        'c', 39,
        'f', 15,
        'i', 16,
        'p', 18,
        'r', 26,
        's', 50,
        't', 41,
        'u', 34,
        'v', 20,
        '{', 58,
        '}', 59,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        ' ', 2,
        '"', 10,
        '(', 108,
        ')', 3,
        ',', 113,
        ';', 116,
        '<', 104,
        '=', 4,
        '>', 103,
        'c', 39,
        'f', 15,
        'i', 16,
        'p', 18,
        'r', 26,
        's', 50,
        't', 41,
        'u', 34,
        'v', 20,
        '{', 58,
        '}', 59,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(109);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(111);
      if (lookahead == '=') ADVANCE(105);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(112);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(6);
      if (lookahead == '"') ADVANCE(10);
      if (lookahead == 'f') ADVANCE(63);
      if (lookahead == 't') ADVANCE(73);
      if (lookahead == '{') ADVANCE(110);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(6);
      if (lookahead == '"') ADVANCE(10);
      if (lookahead == 'f') ADVANCE(63);
      if (lookahead == 't') ADVANCE(73);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 8:
      ADVANCE_MAP(
        ' ', 107,
        'c', 39,
        'f', 14,
        'i', 16,
        'r', 26,
        's', 52,
        'v', 20,
        '}', 59,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(8);
      END_STATE();
    case 9:
      ADVANCE_MAP(
        '"', 10,
        ')', 3,
        ',', 5,
        'c', 72,
        'f', 63,
        'i', 68,
        'r', 65,
        't', 73,
        'v', 64,
        '{', 58,
        '}', 59,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 10:
      if (lookahead == '"') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == ')') ADVANCE(3);
      if (lookahead == '}') ADVANCE(59);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 12:
      if (lookahead == '2') ADVANCE(61);
      END_STATE();
    case 13:
      if (lookahead == '2') ADVANCE(60);
      END_STATE();
    case 14:
      if (lookahead == '3') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == '3') ADVANCE(12);
      if (lookahead == 'a') ADVANCE(33);
      if (lookahead == 'n') ADVANCE(89);
      END_STATE();
    case 16:
      if (lookahead == '3') ADVANCE(13);
      if (lookahead == 'f') ADVANCE(99);
      END_STATE();
    case 17:
      if (lookahead == '=') ADVANCE(105);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 20:
      if (lookahead == 'a') ADVANCE(43);
      END_STATE();
    case 21:
      if (lookahead == 'c') ADVANCE(32);
      END_STATE();
    case 22:
      if (lookahead == 'c') ADVANCE(49);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(85);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(87);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(98);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 27:
      if (lookahead == 'g') ADVANCE(62);
      END_STATE();
    case 28:
      if (lookahead == 'g') ADVANCE(25);
      END_STATE();
    case 29:
      if (lookahead == 'i') ADVANCE(38);
      END_STATE();
    case 30:
      if (lookahead == 'i') ADVANCE(38);
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 31:
      if (lookahead == 'i') ADVANCE(40);
      END_STATE();
    case 32:
      if (lookahead == 'k') ADVANCE(19);
      END_STATE();
    case 33:
      if (lookahead == 'l') ADVANCE(46);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 35:
      if (lookahead == 'n') ADVANCE(47);
      END_STATE();
    case 36:
      if (lookahead == 'n') ADVANCE(96);
      END_STATE();
    case 37:
      if (lookahead == 'n') ADVANCE(90);
      END_STATE();
    case 38:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 39:
      if (lookahead == 'o') ADVANCE(35);
      END_STATE();
    case 40:
      if (lookahead == 'o') ADVANCE(36);
      END_STATE();
    case 41:
      if (lookahead == 'r') ADVANCE(53);
      END_STATE();
    case 42:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 43:
      if (lookahead == 'r') ADVANCE(92);
      END_STATE();
    case 44:
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 45:
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 46:
      if (lookahead == 's') ADVANCE(24);
      END_STATE();
    case 47:
      if (lookahead == 's') ADVANCE(48);
      END_STATE();
    case 48:
      if (lookahead == 't') ADVANCE(94);
      END_STATE();
    case 49:
      if (lookahead == 't') ADVANCE(97);
      END_STATE();
    case 50:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 51:
      if (lookahead == 't') ADVANCE(54);
      END_STATE();
    case 52:
      if (lookahead == 't') ADVANCE(44);
      END_STATE();
    case 53:
      if (lookahead == 'u') ADVANCE(23);
      END_STATE();
    case 54:
      if (lookahead == 'u') ADVANCE(45);
      END_STATE();
    case 55:
      if (eof) ADVANCE(57);
      if (lookahead == '\n') ADVANCE(114);
      if (lookahead == '"') ADVANCE(10);
      if (lookahead == ';') ADVANCE(116);
      if (lookahead == 'f') ADVANCE(63);
      if (lookahead == 't') ADVANCE(73);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(55);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 56:
      if (eof) ADVANCE(57);
      if (lookahead == '\n') ADVANCE(115);
      if (lookahead == ' ') ADVANCE(106);
      if (lookahead == ';') ADVANCE(116);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_i32);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_f32);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(69);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(74);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(79);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(86);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(88);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(100);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(77);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(76);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(91);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(70);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(80);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(93);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(71);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(78);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(67);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(95);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(81);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(66);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(75);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_int);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_true);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_true);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_false);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_false);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_fn_keyword);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_return_keyword);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_return_keyword);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_var_keyword);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_var_keyword);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_const_keyword);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_const_keyword);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_union_keyword);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_struct_keyword);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_package_keyword);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_if_keyword);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_if_keyword);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_greater_or_equal_than_operator);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_less_or_equal_than_operator);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_greater_than_operator);
      if (lookahead == '=') ADVANCE(101);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_less_than_operator);
      if (lookahead == '=') ADVANCE(102);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_equality_operator);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == '\n') ADVANCE(115);
      if (lookahead == ' ') ADVANCE(106);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(107);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_LBRACE2);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_COMMA2);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(114);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(115);
      if (lookahead == ' ') ADVANCE(106);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 9},
  [10] = {.lex_state = 7},
  [11] = {.lex_state = 7},
  [12] = {.lex_state = 7},
  [13] = {.lex_state = 7},
  [14] = {.lex_state = 7},
  [15] = {.lex_state = 7},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 55},
  [18] = {.lex_state = 7},
  [19] = {.lex_state = 7},
  [20] = {.lex_state = 7},
  [21] = {.lex_state = 8},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 8},
  [24] = {.lex_state = 8},
  [25] = {.lex_state = 8},
  [26] = {.lex_state = 8},
  [27] = {.lex_state = 8},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 11},
  [33] = {.lex_state = 8},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 55},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 11},
  [44] = {.lex_state = 11},
  [45] = {.lex_state = 55},
  [46] = {.lex_state = 56},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 11},
  [50] = {.lex_state = 56},
  [51] = {.lex_state = 56},
  [52] = {.lex_state = 56},
  [53] = {.lex_state = 11},
  [54] = {.lex_state = 11},
  [55] = {.lex_state = 55},
  [56] = {.lex_state = 55},
  [57] = {.lex_state = 55},
  [58] = {.lex_state = 55},
  [59] = {.lex_state = 55},
  [60] = {.lex_state = 11},
  [61] = {.lex_state = 55},
  [62] = {.lex_state = 55},
  [63] = {.lex_state = 55},
  [64] = {.lex_state = 11},
  [65] = {.lex_state = 55},
  [66] = {.lex_state = 55},
  [67] = {.lex_state = 55},
  [68] = {.lex_state = 55},
  [69] = {.lex_state = 55},
  [70] = {.lex_state = 55},
  [71] = {.lex_state = 55},
  [72] = {.lex_state = 55},
  [73] = {.lex_state = 55},
  [74] = {.lex_state = 9},
  [75] = {.lex_state = 9},
  [76] = {.lex_state = 9},
  [77] = {.lex_state = 9},
  [78] = {.lex_state = 9},
  [79] = {.lex_state = 11},
  [80] = {.lex_state = 9},
  [81] = {.lex_state = 9},
  [82] = {.lex_state = 9},
  [83] = {.lex_state = 11},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 8},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 7},
  [90] = {.lex_state = 7},
  [91] = {.lex_state = 8},
  [92] = {.lex_state = 8},
  [93] = {.lex_state = 8},
  [94] = {.lex_state = 8},
  [95] = {.lex_state = 8},
  [96] = {.lex_state = 8},
  [97] = {.lex_state = 8},
  [98] = {.lex_state = 11},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 8},
  [101] = {.lex_state = 8},
  [102] = {.lex_state = 11},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 8},
  [105] = {.lex_state = 11},
  [106] = {.lex_state = 11},
  [107] = {.lex_state = 11},
  [108] = {.lex_state = 8},
  [109] = {.lex_state = 11},
  [110] = {.lex_state = 8},
  [111] = {.lex_state = 8},
  [112] = {.lex_state = 8},
  [113] = {.lex_state = 8},
  [114] = {.lex_state = 8},
  [115] = {.lex_state = 9},
  [116] = {.lex_state = 8},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 8},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 8},
  [122] = {.lex_state = 8},
  [123] = {.lex_state = 8},
  [124] = {.lex_state = 11},
  [125] = {.lex_state = 11},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 8},
  [128] = {.lex_state = 8},
  [129] = {.lex_state = 8},
  [130] = {.lex_state = 8},
  [131] = {.lex_state = 8},
  [132] = {.lex_state = 11},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_i32] = ACTIONS(1),
    [anon_sym_f32] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_int] = ACTIONS(1),
    [sym_true] = ACTIONS(1),
    [sym_false] = ACTIONS(1),
    [sym_fn_keyword] = ACTIONS(1),
    [sym_return_keyword] = ACTIONS(1),
    [sym_var_keyword] = ACTIONS(1),
    [sym_const_keyword] = ACTIONS(1),
    [sym_union_keyword] = ACTIONS(1),
    [sym_struct_keyword] = ACTIONS(1),
    [sym_package_keyword] = ACTIONS(1),
    [sym_if_keyword] = ACTIONS(1),
    [sym_greater_or_equal_than_operator] = ACTIONS(1),
    [sym_less_or_equal_than_operator] = ACTIONS(1),
    [sym_greater_than_operator] = ACTIONS(1),
    [sym_less_than_operator] = ACTIONS(1),
    [sym_equality_operator] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE2] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA2] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(86),
    [sym__definition] = STATE(45),
    [sym__statement] = STATE(45),
    [sym_function_definition] = STATE(45),
    [sym_struct_definition] = STATE(45),
    [sym_union_definition] = STATE(45),
    [sym_package_definition] = STATE(45),
    [sym_const_statement] = STATE(45),
    [sym_var_statement] = STATE(45),
    [sym_return_statement] = STATE(45),
    [sym_if_statement] = STATE(45),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_fn_keyword] = ACTIONS(5),
    [sym_return_keyword] = ACTIONS(7),
    [sym_var_keyword] = ACTIONS(9),
    [sym_const_keyword] = ACTIONS(11),
    [sym_union_keyword] = ACTIONS(13),
    [sym_struct_keyword] = ACTIONS(15),
    [sym_package_keyword] = ACTIONS(17),
    [sym_if_keyword] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      sym_fn_keyword,
    ACTIONS(26), 1,
      sym_return_keyword,
    ACTIONS(29), 1,
      sym_var_keyword,
    ACTIONS(32), 1,
      sym_const_keyword,
    ACTIONS(35), 1,
      sym_union_keyword,
    ACTIONS(38), 1,
      sym_struct_keyword,
    ACTIONS(41), 1,
      sym_package_keyword,
    ACTIONS(44), 1,
      sym_if_keyword,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
    STATE(73), 10,
      sym__definition,
      sym__statement,
      sym_function_definition,
      sym_struct_definition,
      sym_union_definition,
      sym_package_definition,
      sym_const_statement,
      sym_var_statement,
      sym_return_statement,
      sym_if_statement,
  [43] = 11,
    ACTIONS(5), 1,
      sym_fn_keyword,
    ACTIONS(7), 1,
      sym_return_keyword,
    ACTIONS(9), 1,
      sym_var_keyword,
    ACTIONS(11), 1,
      sym_const_keyword,
    ACTIONS(13), 1,
      sym_union_keyword,
    ACTIONS(15), 1,
      sym_struct_keyword,
    ACTIONS(17), 1,
      sym_package_keyword,
    ACTIONS(19), 1,
      sym_if_keyword,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
    STATE(41), 10,
      sym__definition,
      sym__statement,
      sym_function_definition,
      sym_struct_definition,
      sym_union_definition,
      sym_package_definition,
      sym_const_statement,
      sym_var_statement,
      sym_return_statement,
      sym_if_statement,
  [86] = 6,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    ACTIONS(51), 1,
      sym_return_keyword,
    ACTIONS(53), 1,
      sym_var_keyword,
    ACTIONS(55), 1,
      sym_const_keyword,
    ACTIONS(57), 1,
      sym_if_keyword,
    STATE(6), 6,
      sym__statement,
      sym_const_statement,
      sym_var_statement,
      sym_return_statement,
      sym_if_statement,
      aux_sym_block_repeat1,
  [110] = 6,
    ACTIONS(51), 1,
      sym_return_keyword,
    ACTIONS(53), 1,
      sym_var_keyword,
    ACTIONS(55), 1,
      sym_const_keyword,
    ACTIONS(57), 1,
      sym_if_keyword,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    STATE(4), 6,
      sym__statement,
      sym_const_statement,
      sym_var_statement,
      sym_return_statement,
      sym_if_statement,
      aux_sym_block_repeat1,
  [134] = 6,
    ACTIONS(61), 1,
      anon_sym_RBRACE,
    ACTIONS(63), 1,
      sym_return_keyword,
    ACTIONS(66), 1,
      sym_var_keyword,
    ACTIONS(69), 1,
      sym_const_keyword,
    ACTIONS(72), 1,
      sym_if_keyword,
    STATE(6), 6,
      sym__statement,
      sym_const_statement,
      sym_var_statement,
      sym_return_statement,
      sym_if_statement,
      aux_sym_block_repeat1,
  [158] = 6,
    ACTIONS(51), 1,
      sym_return_keyword,
    ACTIONS(53), 1,
      sym_var_keyword,
    ACTIONS(55), 1,
      sym_const_keyword,
    ACTIONS(57), 1,
      sym_if_keyword,
    ACTIONS(75), 1,
      anon_sym_RBRACE,
    STATE(6), 6,
      sym__statement,
      sym_const_statement,
      sym_var_statement,
      sym_return_statement,
      sym_if_statement,
      aux_sym_block_repeat1,
  [182] = 6,
    ACTIONS(51), 1,
      sym_return_keyword,
    ACTIONS(53), 1,
      sym_var_keyword,
    ACTIONS(55), 1,
      sym_const_keyword,
    ACTIONS(57), 1,
      sym_if_keyword,
    ACTIONS(77), 1,
      anon_sym_RBRACE,
    STATE(7), 6,
      sym__statement,
      sym_const_statement,
      sym_var_statement,
      sym_return_statement,
      sym_if_statement,
      aux_sym_block_repeat1,
  [206] = 6,
    ACTIONS(79), 1,
      anon_sym_RBRACE,
    ACTIONS(81), 1,
      sym_identifier,
    STATE(40), 1,
      sym_constant,
    ACTIONS(83), 2,
      sym_string,
      sym_int,
    ACTIONS(85), 2,
      sym_true,
      sym_false,
    ACTIONS(87), 4,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [230] = 7,
    ACTIONS(89), 1,
      sym_identifier,
    STATE(51), 1,
      sym_constant,
    STATE(67), 1,
      sym_expression,
    STATE(127), 1,
      sym__simple_expression,
    ACTIONS(91), 2,
      sym_string,
      sym_int,
    ACTIONS(93), 2,
      sym_true,
      sym_false,
    STATE(58), 2,
      sym__boolean_expression,
      sym__comparison_expression,
  [255] = 6,
    ACTIONS(95), 1,
      sym_identifier,
    STATE(93), 1,
      sym_expression,
    ACTIONS(97), 2,
      sym_string,
      sym_int,
    ACTIONS(99), 2,
      sym_true,
      sym_false,
    STATE(95), 2,
      sym__boolean_expression,
      sym__comparison_expression,
    STATE(100), 2,
      sym__simple_expression,
      sym_constant,
  [278] = 6,
    ACTIONS(95), 1,
      sym_identifier,
    STATE(121), 1,
      sym_expression,
    ACTIONS(97), 2,
      sym_string,
      sym_int,
    ACTIONS(99), 2,
      sym_true,
      sym_false,
    STATE(95), 2,
      sym__boolean_expression,
      sym__comparison_expression,
    STATE(100), 2,
      sym__simple_expression,
      sym_constant,
  [301] = 7,
    ACTIONS(101), 1,
      sym_identifier,
    STATE(52), 1,
      sym_constant,
    STATE(55), 1,
      sym_expression,
    STATE(127), 1,
      sym__simple_expression,
    ACTIONS(91), 2,
      sym_string,
      sym_int,
    ACTIONS(93), 2,
      sym_true,
      sym_false,
    STATE(58), 2,
      sym__boolean_expression,
      sym__comparison_expression,
  [326] = 7,
    ACTIONS(103), 1,
      sym_identifier,
    STATE(24), 1,
      sym_constant,
    STATE(34), 1,
      sym_expression,
    STATE(128), 1,
      sym__simple_expression,
    ACTIONS(97), 2,
      sym_string,
      sym_int,
    ACTIONS(105), 2,
      sym_true,
      sym_false,
    STATE(30), 2,
      sym__boolean_expression,
      sym__comparison_expression,
  [351] = 7,
    ACTIONS(107), 1,
      sym_identifier,
    STATE(26), 1,
      sym_constant,
    STATE(35), 1,
      sym_expression,
    STATE(128), 1,
      sym__simple_expression,
    ACTIONS(97), 2,
      sym_string,
      sym_int,
    ACTIONS(105), 2,
      sym_true,
      sym_false,
    STATE(30), 2,
      sym__boolean_expression,
      sym__comparison_expression,
  [376] = 1,
    ACTIONS(21), 9,
      ts_builtin_sym_end,
      sym_fn_keyword,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_union_keyword,
      sym_struct_keyword,
      sym_package_keyword,
      sym_if_keyword,
  [388] = 5,
    ACTIONS(87), 1,
      anon_sym_SEMI,
    ACTIONS(109), 1,
      sym_identifier,
    STATE(57), 1,
      sym_constant,
    ACTIONS(79), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
    ACTIONS(111), 4,
      sym_string,
      sym_int,
      sym_true,
      sym_false,
  [408] = 4,
    ACTIONS(113), 1,
      sym_identifier,
    ACTIONS(97), 2,
      sym_string,
      sym_int,
    ACTIONS(115), 2,
      sym_true,
      sym_false,
    STATE(108), 2,
      sym__simple_expression,
      sym_constant,
  [424] = 4,
    ACTIONS(117), 1,
      sym_identifier,
    ACTIONS(83), 2,
      sym_string,
      sym_int,
    ACTIONS(85), 2,
      sym_true,
      sym_false,
    STATE(39), 2,
      sym__simple_expression,
      sym_constant,
  [440] = 4,
    ACTIONS(119), 1,
      sym_identifier,
    ACTIONS(111), 2,
      sym_true,
      sym_false,
    ACTIONS(121), 2,
      sym_string,
      sym_int,
    STATE(56), 2,
      sym__simple_expression,
      sym_constant,
  [456] = 4,
    ACTIONS(125), 1,
      anon_sym_SPACE,
    STATE(23), 1,
      aux_sym_struct_field_repeat1,
    STATE(103), 1,
      sym_type,
    ACTIONS(123), 3,
      anon_sym_i32,
      anon_sym_f32,
      anon_sym_string,
  [471] = 3,
    STATE(94), 1,
      sym__comparison_operator,
    ACTIONS(129), 2,
      sym_greater_than_operator,
      sym_less_than_operator,
    ACTIONS(127), 3,
      sym_greater_or_equal_than_operator,
      sym_less_or_equal_than_operator,
      sym_equality_operator,
  [484] = 4,
    ACTIONS(131), 1,
      anon_sym_SPACE,
    STATE(33), 1,
      aux_sym_struct_field_repeat1,
    STATE(119), 1,
      sym_type,
    ACTIONS(123), 3,
      anon_sym_i32,
      anon_sym_f32,
      anon_sym_string,
  [499] = 2,
    ACTIONS(135), 1,
      anon_sym_SPACE,
    ACTIONS(133), 5,
      anon_sym_RBRACE,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [510] = 2,
    ACTIONS(139), 1,
      anon_sym_SPACE,
    ACTIONS(137), 5,
      anon_sym_RBRACE,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [521] = 2,
    ACTIONS(135), 1,
      anon_sym_SPACE,
    ACTIONS(141), 5,
      anon_sym_RBRACE,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [532] = 2,
    ACTIONS(139), 1,
      anon_sym_SPACE,
    ACTIONS(143), 5,
      anon_sym_RBRACE,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [543] = 3,
    STATE(116), 1,
      sym__comparison_operator,
    ACTIONS(148), 2,
      sym_greater_than_operator,
      sym_less_than_operator,
    ACTIONS(146), 3,
      sym_greater_or_equal_than_operator,
      sym_less_or_equal_than_operator,
      sym_equality_operator,
  [556] = 3,
    STATE(118), 1,
      sym__comparison_operator,
    ACTIONS(152), 2,
      sym_greater_than_operator,
      sym_less_than_operator,
    ACTIONS(150), 3,
      sym_greater_or_equal_than_operator,
      sym_less_or_equal_than_operator,
      sym_equality_operator,
  [569] = 1,
    ACTIONS(154), 5,
      anon_sym_RBRACE,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [577] = 1,
    ACTIONS(139), 5,
      anon_sym_RBRACE,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [585] = 5,
    ACTIONS(156), 1,
      sym_identifier,
    ACTIONS(158), 1,
      anon_sym_RPAREN,
    STATE(64), 1,
      aux_sym_parameters_repeat1,
    STATE(76), 1,
      sym_parameter,
    STATE(117), 1,
      sym_parameters,
  [601] = 3,
    ACTIONS(162), 1,
      anon_sym_SPACE,
    STATE(33), 1,
      aux_sym_struct_field_repeat1,
    ACTIONS(160), 3,
      anon_sym_i32,
      anon_sym_f32,
      anon_sym_string,
  [613] = 1,
    ACTIONS(165), 5,
      anon_sym_RBRACE,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [621] = 1,
    ACTIONS(167), 5,
      anon_sym_RBRACE,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [629] = 1,
    ACTIONS(169), 5,
      anon_sym_RBRACE,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [637] = 1,
    ACTIONS(171), 5,
      anon_sym_RBRACE,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [645] = 1,
    ACTIONS(173), 5,
      anon_sym_RBRACE,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [653] = 1,
    ACTIONS(175), 5,
      anon_sym_RBRACE,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [661] = 1,
    ACTIONS(177), 5,
      anon_sym_RBRACE,
      sym_return_keyword,
      sym_var_keyword,
      sym_const_keyword,
      sym_if_keyword,
  [669] = 4,
    ACTIONS(179), 1,
      ts_builtin_sym_end,
    ACTIONS(181), 1,
      anon_sym_LF,
    ACTIONS(183), 1,
      anon_sym_SEMI,
    STATE(16), 1,
      sym__terminator,
  [682] = 2,
    STATE(114), 1,
      sym_type,
    ACTIONS(185), 3,
      anon_sym_i32,
      anon_sym_f32,
      anon_sym_string,
  [691] = 3,
    ACTIONS(187), 1,
      anon_sym_RBRACE,
    ACTIONS(189), 1,
      sym_identifier,
    STATE(53), 2,
      sym_struct_field,
      aux_sym_struct_definition_repeat1,
  [702] = 3,
    ACTIONS(189), 1,
      sym_identifier,
    ACTIONS(191), 1,
      anon_sym_RBRACE,
    STATE(54), 2,
      sym_struct_field,
      aux_sym_struct_definition_repeat1,
  [713] = 4,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(181), 1,
      anon_sym_LF,
    ACTIONS(183), 1,
      anon_sym_SEMI,
    STATE(16), 1,
      sym__terminator,
  [726] = 3,
    ACTIONS(137), 1,
      anon_sym_SPACE,
    ACTIONS(193), 1,
      ts_builtin_sym_end,
    ACTIONS(143), 2,
      anon_sym_LF,
      anon_sym_SEMI,
  [737] = 2,
    STATE(97), 1,
      sym_type,
    ACTIONS(185), 3,
      anon_sym_i32,
      anon_sym_f32,
      anon_sym_string,
  [746] = 2,
    STATE(74), 1,
      sym_type,
    ACTIONS(196), 3,
      anon_sym_i32,
      anon_sym_f32,
      anon_sym_string,
  [755] = 3,
    ACTIONS(198), 1,
      anon_sym_RBRACE,
    ACTIONS(200), 1,
      sym_identifier,
    STATE(49), 2,
      sym_struct_field,
      aux_sym_struct_definition_repeat1,
  [766] = 2,
    ACTIONS(139), 1,
      ts_builtin_sym_end,
    ACTIONS(137), 3,
      anon_sym_SPACE,
      anon_sym_LF,
      anon_sym_SEMI,
  [775] = 3,
    ACTIONS(165), 1,
      ts_builtin_sym_end,
    ACTIONS(203), 1,
      anon_sym_SPACE,
    ACTIONS(133), 2,
      anon_sym_LF,
      anon_sym_SEMI,
  [786] = 3,
    ACTIONS(167), 1,
      ts_builtin_sym_end,
    ACTIONS(203), 1,
      anon_sym_SPACE,
    ACTIONS(141), 2,
      anon_sym_LF,
      anon_sym_SEMI,
  [797] = 3,
    ACTIONS(189), 1,
      sym_identifier,
    ACTIONS(205), 1,
      anon_sym_RBRACE,
    STATE(49), 2,
      sym_struct_field,
      aux_sym_struct_definition_repeat1,
  [808] = 3,
    ACTIONS(189), 1,
      sym_identifier,
    ACTIONS(207), 1,
      anon_sym_RBRACE,
    STATE(49), 2,
      sym_struct_field,
      aux_sym_struct_definition_repeat1,
  [819] = 2,
    ACTIONS(141), 1,
      anon_sym_SEMI,
    ACTIONS(167), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [827] = 2,
    ACTIONS(209), 1,
      anon_sym_SEMI,
    ACTIONS(175), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [835] = 2,
    ACTIONS(211), 1,
      anon_sym_SEMI,
    ACTIONS(177), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [843] = 2,
    ACTIONS(213), 1,
      anon_sym_SEMI,
    ACTIONS(154), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [851] = 2,
    ACTIONS(137), 1,
      anon_sym_SEMI,
    ACTIONS(139), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [859] = 3,
    ACTIONS(215), 1,
      sym_identifier,
    STATE(60), 1,
      aux_sym_parameters_repeat1,
    STATE(115), 1,
      sym_parameter,
  [869] = 2,
    ACTIONS(218), 1,
      anon_sym_SEMI,
    ACTIONS(173), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [877] = 2,
    ACTIONS(222), 1,
      anon_sym_SEMI,
    ACTIONS(220), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [885] = 2,
    ACTIONS(226), 1,
      anon_sym_SEMI,
    ACTIONS(224), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [893] = 3,
    ACTIONS(156), 1,
      sym_identifier,
    STATE(60), 1,
      aux_sym_parameters_repeat1,
    STATE(77), 1,
      sym_parameter,
  [903] = 2,
    ACTIONS(228), 1,
      anon_sym_SEMI,
    ACTIONS(171), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [911] = 2,
    ACTIONS(230), 1,
      anon_sym_SEMI,
    ACTIONS(169), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [919] = 2,
    ACTIONS(133), 1,
      anon_sym_SEMI,
    ACTIONS(165), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [927] = 2,
    ACTIONS(234), 1,
      anon_sym_SEMI,
    ACTIONS(232), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [935] = 2,
    ACTIONS(238), 1,
      anon_sym_SEMI,
    ACTIONS(236), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [943] = 2,
    ACTIONS(242), 1,
      anon_sym_SEMI,
    ACTIONS(240), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [951] = 2,
    ACTIONS(246), 1,
      anon_sym_SEMI,
    ACTIONS(244), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [959] = 2,
    ACTIONS(250), 1,
      anon_sym_SEMI,
    ACTIONS(248), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [967] = 3,
    ACTIONS(181), 1,
      anon_sym_LF,
    ACTIONS(183), 1,
      anon_sym_SEMI,
    STATE(16), 1,
      sym__terminator,
  [977] = 1,
    ACTIONS(252), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [982] = 2,
    ACTIONS(254), 1,
      anon_sym_LBRACE,
    STATE(66), 1,
      sym_block,
  [989] = 2,
    ACTIONS(256), 1,
      anon_sym_RPAREN,
    ACTIONS(258), 1,
      anon_sym_COMMA,
  [996] = 2,
    ACTIONS(258), 1,
      anon_sym_COMMA,
    ACTIONS(260), 1,
      anon_sym_RPAREN,
  [1003] = 2,
    ACTIONS(254), 1,
      anon_sym_LBRACE,
    STATE(70), 1,
      sym_block,
  [1010] = 1,
    ACTIONS(262), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1015] = 2,
    ACTIONS(264), 1,
      anon_sym_LBRACE,
    STATE(36), 1,
      sym_block,
  [1022] = 2,
    ACTIONS(254), 1,
      anon_sym_LBRACE,
    STATE(62), 1,
      sym_block,
  [1029] = 1,
    ACTIONS(266), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1034] = 1,
    ACTIONS(268), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1039] = 1,
    ACTIONS(270), 1,
      anon_sym_EQ,
  [1043] = 1,
    ACTIONS(272), 1,
      anon_sym_SPACE,
  [1047] = 1,
    ACTIONS(274), 1,
      ts_builtin_sym_end,
  [1051] = 1,
    ACTIONS(276), 1,
      anon_sym_EQ,
  [1055] = 1,
    ACTIONS(278), 1,
      anon_sym_EQ,
  [1059] = 1,
    ACTIONS(280), 1,
      anon_sym_LBRACE2,
  [1063] = 1,
    ACTIONS(282), 1,
      anon_sym_LBRACE2,
  [1067] = 1,
    ACTIONS(284), 1,
      anon_sym_SPACE,
  [1071] = 1,
    ACTIONS(193), 1,
      anon_sym_SPACE,
  [1075] = 1,
    ACTIONS(286), 1,
      anon_sym_SPACE,
  [1079] = 1,
    ACTIONS(288), 1,
      anon_sym_SPACE,
  [1083] = 1,
    ACTIONS(154), 1,
      anon_sym_SPACE,
  [1087] = 1,
    ACTIONS(266), 1,
      anon_sym_SPACE,
  [1091] = 1,
    ACTIONS(290), 1,
      anon_sym_SPACE,
  [1095] = 1,
    ACTIONS(292), 1,
      sym_identifier,
  [1099] = 1,
    ACTIONS(266), 1,
      anon_sym_COMMA2,
  [1103] = 1,
    ACTIONS(294), 1,
      anon_sym_SPACE,
  [1107] = 1,
    ACTIONS(296), 1,
      anon_sym_SPACE,
  [1111] = 1,
    ACTIONS(298), 1,
      sym_identifier,
  [1115] = 1,
    ACTIONS(300), 1,
      anon_sym_COMMA2,
  [1119] = 1,
    ACTIONS(302), 1,
      anon_sym_SPACE,
  [1123] = 1,
    ACTIONS(304), 1,
      sym_identifier,
  [1127] = 1,
    ACTIONS(306), 1,
      sym_identifier,
  [1131] = 1,
    ACTIONS(308), 1,
      sym_identifier,
  [1135] = 1,
    ACTIONS(175), 1,
      anon_sym_SPACE,
  [1139] = 1,
    ACTIONS(310), 1,
      sym_identifier,
  [1143] = 1,
    ACTIONS(312), 1,
      anon_sym_SPACE,
  [1147] = 1,
    ACTIONS(314), 1,
      anon_sym_SPACE,
  [1151] = 1,
    ACTIONS(316), 1,
      anon_sym_SPACE,
  [1155] = 1,
    ACTIONS(318), 1,
      anon_sym_SPACE,
  [1159] = 1,
    ACTIONS(320), 1,
      anon_sym_SPACE,
  [1163] = 1,
    ACTIONS(258), 1,
      anon_sym_COMMA,
  [1167] = 1,
    ACTIONS(322), 1,
      anon_sym_SPACE,
  [1171] = 1,
    ACTIONS(324), 1,
      anon_sym_RPAREN,
  [1175] = 1,
    ACTIONS(326), 1,
      anon_sym_SPACE,
  [1179] = 1,
    ACTIONS(328), 1,
      anon_sym_COMMA2,
  [1183] = 1,
    ACTIONS(330), 1,
      anon_sym_EQ,
  [1187] = 1,
    ACTIONS(332), 1,
      anon_sym_SPACE,
  [1191] = 1,
    ACTIONS(334), 1,
      anon_sym_SPACE,
  [1195] = 1,
    ACTIONS(336), 1,
      anon_sym_SPACE,
  [1199] = 1,
    ACTIONS(338), 1,
      sym_identifier,
  [1203] = 1,
    ACTIONS(340), 1,
      sym_identifier,
  [1207] = 1,
    ACTIONS(342), 1,
      anon_sym_LPAREN,
  [1211] = 1,
    ACTIONS(344), 1,
      anon_sym_SPACE,
  [1215] = 1,
    ACTIONS(346), 1,
      anon_sym_SPACE,
  [1219] = 1,
    ACTIONS(348), 1,
      anon_sym_SPACE,
  [1223] = 1,
    ACTIONS(350), 1,
      anon_sym_SPACE,
  [1227] = 1,
    ACTIONS(352), 1,
      anon_sym_SPACE,
  [1231] = 1,
    ACTIONS(354), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 43,
  [SMALL_STATE(4)] = 86,
  [SMALL_STATE(5)] = 110,
  [SMALL_STATE(6)] = 134,
  [SMALL_STATE(7)] = 158,
  [SMALL_STATE(8)] = 182,
  [SMALL_STATE(9)] = 206,
  [SMALL_STATE(10)] = 230,
  [SMALL_STATE(11)] = 255,
  [SMALL_STATE(12)] = 278,
  [SMALL_STATE(13)] = 301,
  [SMALL_STATE(14)] = 326,
  [SMALL_STATE(15)] = 351,
  [SMALL_STATE(16)] = 376,
  [SMALL_STATE(17)] = 388,
  [SMALL_STATE(18)] = 408,
  [SMALL_STATE(19)] = 424,
  [SMALL_STATE(20)] = 440,
  [SMALL_STATE(21)] = 456,
  [SMALL_STATE(22)] = 471,
  [SMALL_STATE(23)] = 484,
  [SMALL_STATE(24)] = 499,
  [SMALL_STATE(25)] = 510,
  [SMALL_STATE(26)] = 521,
  [SMALL_STATE(27)] = 532,
  [SMALL_STATE(28)] = 543,
  [SMALL_STATE(29)] = 556,
  [SMALL_STATE(30)] = 569,
  [SMALL_STATE(31)] = 577,
  [SMALL_STATE(32)] = 585,
  [SMALL_STATE(33)] = 601,
  [SMALL_STATE(34)] = 613,
  [SMALL_STATE(35)] = 621,
  [SMALL_STATE(36)] = 629,
  [SMALL_STATE(37)] = 637,
  [SMALL_STATE(38)] = 645,
  [SMALL_STATE(39)] = 653,
  [SMALL_STATE(40)] = 661,
  [SMALL_STATE(41)] = 669,
  [SMALL_STATE(42)] = 682,
  [SMALL_STATE(43)] = 691,
  [SMALL_STATE(44)] = 702,
  [SMALL_STATE(45)] = 713,
  [SMALL_STATE(46)] = 726,
  [SMALL_STATE(47)] = 737,
  [SMALL_STATE(48)] = 746,
  [SMALL_STATE(49)] = 755,
  [SMALL_STATE(50)] = 766,
  [SMALL_STATE(51)] = 775,
  [SMALL_STATE(52)] = 786,
  [SMALL_STATE(53)] = 797,
  [SMALL_STATE(54)] = 808,
  [SMALL_STATE(55)] = 819,
  [SMALL_STATE(56)] = 827,
  [SMALL_STATE(57)] = 835,
  [SMALL_STATE(58)] = 843,
  [SMALL_STATE(59)] = 851,
  [SMALL_STATE(60)] = 859,
  [SMALL_STATE(61)] = 869,
  [SMALL_STATE(62)] = 877,
  [SMALL_STATE(63)] = 885,
  [SMALL_STATE(64)] = 893,
  [SMALL_STATE(65)] = 903,
  [SMALL_STATE(66)] = 911,
  [SMALL_STATE(67)] = 919,
  [SMALL_STATE(68)] = 927,
  [SMALL_STATE(69)] = 935,
  [SMALL_STATE(70)] = 943,
  [SMALL_STATE(71)] = 951,
  [SMALL_STATE(72)] = 959,
  [SMALL_STATE(73)] = 967,
  [SMALL_STATE(74)] = 977,
  [SMALL_STATE(75)] = 982,
  [SMALL_STATE(76)] = 989,
  [SMALL_STATE(77)] = 996,
  [SMALL_STATE(78)] = 1003,
  [SMALL_STATE(79)] = 1010,
  [SMALL_STATE(80)] = 1015,
  [SMALL_STATE(81)] = 1022,
  [SMALL_STATE(82)] = 1029,
  [SMALL_STATE(83)] = 1034,
  [SMALL_STATE(84)] = 1039,
  [SMALL_STATE(85)] = 1043,
  [SMALL_STATE(86)] = 1047,
  [SMALL_STATE(87)] = 1051,
  [SMALL_STATE(88)] = 1055,
  [SMALL_STATE(89)] = 1059,
  [SMALL_STATE(90)] = 1063,
  [SMALL_STATE(91)] = 1067,
  [SMALL_STATE(92)] = 1071,
  [SMALL_STATE(93)] = 1075,
  [SMALL_STATE(94)] = 1079,
  [SMALL_STATE(95)] = 1083,
  [SMALL_STATE(96)] = 1087,
  [SMALL_STATE(97)] = 1091,
  [SMALL_STATE(98)] = 1095,
  [SMALL_STATE(99)] = 1099,
  [SMALL_STATE(100)] = 1103,
  [SMALL_STATE(101)] = 1107,
  [SMALL_STATE(102)] = 1111,
  [SMALL_STATE(103)] = 1115,
  [SMALL_STATE(104)] = 1119,
  [SMALL_STATE(105)] = 1123,
  [SMALL_STATE(106)] = 1127,
  [SMALL_STATE(107)] = 1131,
  [SMALL_STATE(108)] = 1135,
  [SMALL_STATE(109)] = 1139,
  [SMALL_STATE(110)] = 1143,
  [SMALL_STATE(111)] = 1147,
  [SMALL_STATE(112)] = 1151,
  [SMALL_STATE(113)] = 1155,
  [SMALL_STATE(114)] = 1159,
  [SMALL_STATE(115)] = 1163,
  [SMALL_STATE(116)] = 1167,
  [SMALL_STATE(117)] = 1171,
  [SMALL_STATE(118)] = 1175,
  [SMALL_STATE(119)] = 1179,
  [SMALL_STATE(120)] = 1183,
  [SMALL_STATE(121)] = 1187,
  [SMALL_STATE(122)] = 1191,
  [SMALL_STATE(123)] = 1195,
  [SMALL_STATE(124)] = 1199,
  [SMALL_STATE(125)] = 1203,
  [SMALL_STATE(126)] = 1207,
  [SMALL_STATE(127)] = 1211,
  [SMALL_STATE(128)] = 1215,
  [SMALL_STATE(129)] = 1219,
  [SMALL_STATE(130)] = 1223,
  [SMALL_STATE(131)] = 1227,
  [SMALL_STATE(132)] = 1231,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(101),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(104),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(112),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(113),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(122),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(123),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(111),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(129),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(130),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(131),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_statement, 5, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__simple_expression, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constant, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_const_statement, 5, 0, 0),
  [143] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym__boolean_expression, 1, 0, 0), REDUCE(sym_constant, 1, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(118),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_struct_field_repeat1, 2, 0, 0),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_field_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_statement, 5, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_statement, 5, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, 0, 1),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comparison_expression, 5, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 3, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [193] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__boolean_expression, 1, 0, 0), REDUCE(sym_constant, 1, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_struct_definition_repeat1, 2, 0, 0),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_struct_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__simple_expression, 1, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__comparison_expression, 5, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 3, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [215] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(110),
  [218] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 8, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 8, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_definition, 6, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_union_definition, 6, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 5, 0, 1),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_definition, 6, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct_definition, 6, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_definition, 3, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_package_definition, 3, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 9, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 9, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_definition, 5, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct_definition, 5, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_definition, 5, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_union_definition, 5, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 1, 0, 0),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2, 0, 0),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 4, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_field, 3, 0, 0),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [274] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_pl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "pl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
